# Generated by Django 6.1.1 on 2026-09-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='updated_at',
        ),
    ]
