# Generated by Django 5.2.17 on 2026-09-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0002_remove_proposition_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
