# Generated by Django 5.2.17 on 2026-09-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0003_proposition_updated_at'),
        ('proposition', '0005_alter_projectmeeting_id_alter_proposition_id'),
    ]

    operations = [
    ]
