# Generated by Django 5.2.17 on 2026-09-22 15:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mission', '0005_alter_mission_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TEXTE', 'Texte'), ('VOCAL', 'Vocal')], default='TEXTE', max_length=10)),
                ('contenu', models.TextField(blank=True, help_text='Contenu du message texte')),
                ('audio_url', models.URLField(blank=True, help_text='URL Cloudinary du fichier audio pour messages vocaux', max_length=500, null=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(help_text='Mission associée à cette conversation', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mission.mission')),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='MessageLu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lecture', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='message.message')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_lus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Messages lus',
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mission', 'date_envoi'], name='message_mes_mission_f3412a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['expediteur', 'date_envoi'], name='message_mes_expedit_64a618_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['destinataire', 'date_envoi'], name='message_mes_destina_0da262_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagelu',
            unique_together={('message', 'utilisateur')},
        ),
    ]
