# Generated by Django 5.2.17 on 2026-09-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio_url',
            field=models.TextField(blank=True, help_text='URL du fichier audio pour messages vocaux', null=True),
        ),
    ]
