# Generated by Django 5.2.17 on 2026-09-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0004_alter_mission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ouverte'), ('IN_PROGRESS', 'En cours de développement'), ('DELIVERED', 'Livrée'), ('COMPLETED', 'Terminée'), ('CLOSED', 'Fermée')], default='OPEN', max_length=20),
        ),
    ]
