# Generated by Django 5.2.17 on 2026-09-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0005_alter_mission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('PENDING_MODERATION', 'En attente de modération'), ('OPEN', 'Ouverte'), ('IN_PROGRESS', 'En cours de développement'), ('DELIVERED', 'Livrée'), ('COMPLETED', 'Terminée'), ('CLOSED', 'Fermée'), ('REJECTED', 'Rejetée')], default='PENDING_MODERATION', max_length=30),
        ),
    ]
