# Generated by Django 5.2.17 on 2026-10-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0007_alter_mission_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('PENDING_MODERATION', 'En attente de modération'), ('OPEN', 'Ouverte'), ('IN_PROGRESS', 'En cours de développement'), ('DELIVERED', 'Livrée'), ('COMPLETED', 'Terminée'), ('CLOSED', 'Fermée'), ('REJECTED', 'Rejetée'), ('CANCELLED', 'Annulée')], default='PENDING_MODERATION', max_length=30),
        ),
    ]
