# Generated by Django 5.2.17 on 2026-09-19 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelance', '0006_alter_diplomeobtenu_id_alter_education_id_and_more'),
        ('mission', '0004_alter_mission_id'),
        ('proposition', '0005_alter_projectmeeting_id_alter_proposition_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultatMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('score_technologies', models.FloatField()),
                ('score_service', models.FloatField()),
                ('score_experience', models.FloatField(blank=True, null=True)),
                ('justification_ia', models.TextField(blank=True, null=True)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('freelance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultats_matching', to='freelance.freelancee')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_matching', to='mission.mission')),
                ('proposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultats_matching', to='proposition.proposition')),
            ],
            options={
                'verbose_name': 'Résultat de matching',
                'verbose_name_plural': 'Résultats de matching',
                'ordering': ['-date_calcul', '-score'],
            },
        ),
    ]
