# Generated by Django 5.2.17 on 2026-09-22 15:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        ('mission', '0005_alter_mission_status'),
        ('paiement', '0001_initial'),
        ('proposition', '0006_merge_20260921_1242'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PROPOSITION_ACCEPTEE', 'Proposition acceptée'), ('PROPOSITION_REJETEE', 'Proposition rejetée'), ('MISSION_DEMARREE', 'Mission démarrée'), ('MISSION_LIVREE', 'Mission livrée'), ('MISSION_COMPLETEE', 'Mission complétée'), ('MISSION_ANNULEE', 'Mission annulée'), ('MISSION_LITIGE', 'Litige ouvert'), ('PAIEMENT_REUSSI', 'Paiement réussi'), ('PAIEMENT_ECHOUE', 'Paiement échoué'), ('NOUVEAU_MESSAGE', 'Nouveau message')], max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('message_obj', models.ForeignKey(blank=True, help_text='Message concerné (pour type NOUVEAU_MESSAGE)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='message.message')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mission.mission')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='paiement.paiement')),
                ('proposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='proposition.proposition')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', '-date_creation'], name='notificatio_utilisa_367521_idx'), models.Index(fields=['utilisateur', 'lue'], name='notificatio_utilisa_dfa632_idx')],
            },
        ),
    ]
