# Generated by Django 5.2.17 on 2026-10-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PROPOSITION_ACCEPTEE', 'Proposition acceptée'), ('PROPOSITION_REJETEE', 'Proposition rejetée'), ('MISSION_DEMARREE', 'Mission démarrée'), ('MISSION_LIVREE', 'Mission livrée'), ('MISSION_COMPLETEE', 'Mission complétée'), ('MISSION_ANNULEE', 'Mission annulée'), ('MISSION_LITIGE', 'Litige ouvert'), ('PAIEMENT_REUSSI', 'Paiement réussi'), ('PAIEMENT_ECHOUE', 'Paiement échoué'), ('NOUVEAU_MESSAGE', 'Nouveau message'), ('MISSION_RECOMMANDEE', 'Mission recommandée')], max_length=30),
        ),
    ]
