# Generated by Django 5.2.17 on 2026-10-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PROPOSITION_ACCEPTEE', 'Proposition acceptée'), ('PROPOSITION_REJETEE', 'Proposition rejetée'), ('MISSION_DEMARREE', 'Mission démarrée'), ('MISSION_LIVREE', 'Mission livrée'), ('MISSION_COMPLETEE', 'Mission complétée'), ('MISSION_ANNULEE', 'Mission annulée'), ('MISSION_LITIGE', 'Litige ouvert'), ('PAIEMENT_REUSSI', 'Paiement réussi'), ('PAIEMENT_ECHOUE', 'Paiement échoué'), ('NOUVEAU_MESSAGE', 'Nouveau message'), ('MISSION_RECOMMANDEE', 'Mission recommandée'), ('CADRAGE_A_LIVRER', 'Cadrage à livrer'), ('LIVRABLE_SOUMIS', 'Livrable soumis'), ('LIVRABLE_VALIDE', 'Livrable validé'), ('LIVRABLE_INVALIDE', 'Livrable invalidé'), ('DEADLINE_REPOUSSEE', 'Deadline repoussée'), ('RETARD_CADRAGE', 'Retard de cadrage'), ('RETARD_VALIDATION', 'Livrable sans réponse'), ('RELANCE_SUIVI', 'Relance'), ('DEMANDE_ANNULATION', "Demande d'annulation"), ('ANNULATION_REFUSEE', 'Annulation refusée')], max_length=30),
        ),
    ]
