# Generated by Django 5.2.17 on 2026-10-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_alter_service_id'),
        ('freelance', '0006_alter_diplomeobtenu_id_alter_education_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancee',
            name='service',
        ),
        migrations.AddField(
            model_name='freelancee',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='freelances', to='Service.service'),
        ),
    ]
