# Generated by Django 5.2.17 on 2026-10-09 23:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcer', '0003_alter_announcer_id'),
        ('freelance', '0007_remove_freelancee_service_freelancee_services'),
        ('mission', '0008_alter_mission_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAnnulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('annonceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_annulation', to='announcer.announcer')),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annulations_decidees', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_annulation', to='mission.mission')),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PHASE_OUVERTE', 'Phase ouverte'), ('PHASE_VALIDEE', 'Phase validée'), ('LIVRABLE_SOUMIS', 'Livrable soumis'), ('LIVRABLE_VALIDE', 'Livrable validé'), ('LIVRABLE_INVALIDE', 'Livrable invalidé'), ('DEADLINE_REPOUSSEE', 'Deadline repoussée'), ('RETARD_CADRAGE', 'Retard de cadrage détecté'), ('RETARD_VALIDATION', 'Retard de validation détecté'), ('RELANCE', 'Relance envoyée'), ('ANNULATION_DEMANDEE', 'Annulation demandée'), ('ANNULATION_ACCEPTEE', 'Annulation acceptée'), ('ANNULATION_REFUSEE', 'Annulation refusée')], max_length=30)),
                ('details', models.TextField(blank=True, default='')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_historique', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='mission.mission')),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Livrable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('lien', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, default='', max_length=3000)),
                ('statut', models.CharField(choices=[('A_VALIDER', 'À valider'), ('VALIDE', 'Validé'), ('INVALIDE', 'Invalidé')], default='A_VALIDER', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('retard_validation_notifie', models.BooleanField(default=False)),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrables', to='freelance.freelancee')),
            ],
            options={
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireLivrable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEXTE', 'Texte'), ('VOCAL', 'Vocal')], max_length=10)),
                ('texte', models.TextField(blank=True, default='', max_length=3000)),
                ('fichier_vocal', models.FileField(blank=True, null=True, upload_to='suivi/vocaux/', validators=[django.core.validators.FileExtensionValidator(['webm', 'ogg', 'mp3', 'm4a', 'wav', 'aac'])])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_livrables', to=settings.AUTH_USER_MODEL)),
                ('livrable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='suivi.livrable')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CADRAGE', 'Cadrage'), ('DEVELOPPEMENT', 'Développement')], max_length=20)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDEE', 'Validée')], default='EN_COURS', max_length=20)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('retard_notifie', models.BooleanField(default=False)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='mission.mission')),
            ],
            options={
                'ordering': ['date_ouverture'],
            },
        ),
        migrations.AddField(
            model_name='livrable',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrables', to='suivi.phase'),
        ),
        migrations.AddConstraint(
            model_name='phase',
            constraint=models.UniqueConstraint(fields=('mission', 'type'), name='unique_phase_par_type_et_mission'),
        ),
    ]
