# Generated by Django 5.2.17 on 2026-10-10 15:01

import django.core.validators
import django.db.models.deletion
import suivi.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcer', '0003_alter_announcer_id'),
        ('freelance', '0007_remove_freelancee_service_freelancee_services'),
        ('mission', '0008_alter_mission_status'),
        ('suivi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentairelivrable',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaires_livrables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentairelivrable',
            name='fichier_vocal',
            field=models.FileField(blank=True, null=True, upload_to=suivi.models.chemin_vocal, validators=[django.core.validators.FileExtensionValidator(['webm', 'ogg', 'mp3', 'm4a', 'wav', 'aac'])]),
        ),
        migrations.AlterField(
            model_name='historique',
            name='action',
            field=models.CharField(choices=[('PHASE_OUVERTE', 'Phase ouverte'), ('PHASE_VALIDEE', 'Phase validée'), ('LIVRABLE_SOUMIS', 'Livrable soumis'), ('LIVRABLE_VALIDE', 'Livrable validé'), ('LIVRABLE_INVALIDE', 'Livrable invalidé'), ('DEADLINE_REPOUSSEE', 'Deadline repoussée'), ('RETARD_CADRAGE', 'Retard de cadrage détecté'), ('RETARD_LIVRAISON', 'Retard de livraison détecté'), ('RETARD_VALIDATION', 'Retard de validation détecté'), ('RELANCE', 'Relance envoyée'), ('ANNULATION_DEMANDEE', 'Annulation demandée'), ('ANNULATION_ACCEPTEE', 'Annulation acceptée'), ('ANNULATION_REFUSEE', 'Annulation refusée')], max_length=30),
        ),
        migrations.AlterField(
            model_name='livrable',
            name='freelance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livrables', to='freelance.freelancee'),
        ),
        migrations.AddConstraint(
            model_name='demandeannulation',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'EN_ATTENTE')), fields=('mission',), name='une_demande_annulation_en_attente_par_mission'),
        ),
    ]
