# Generated by Django 5.2.17 on 2026-09-21 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelance', '0006_alter_diplomeobtenu_id_alter_education_id_and_more'),
        ('proposition', '0003_proposition_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_brut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taux_commission', models.DecimalField(decimal_places=4, max_digits=5)),
                ('montant_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut_collecte', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué')], default='EN_ATTENTE', max_length=20)),
                ('statut_decaissement', models.CharField(choices=[('NON_DECLENCHE', 'Non déclenché'), ('EN_ATTENTE', 'En attente'), ('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué')], default='NON_DECLENCHE', max_length=20)),
                ('reference_collecte', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_decaissement', models.CharField(blank=True, max_length=255, null=True)),
                ('date_collecte', models.DateTimeField(blank=True, null=True)),
                ('date_decaissement', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='proposition.proposition')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('OM', 'Orange Money'), ('WAVE', 'Wave')], max_length=50)),
                ('numero', models.CharField(max_length=20)),
                ('date_confirmation', models.DateTimeField(auto_now=True)),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numeros_paiement', to='freelance.freelancee')),
            ],
            options={
                'unique_together': {('freelance', 'operateur')},
            },
        ),
    ]
